---
- name: create database
  mysql_db:
    name: "{{ servers.db.database }}"
    state: present

- name: create user for database
  mysql_user:
    host: "{{ servers.db.host }}"
    name: "{{ servers.db.username }}"
    password: "{{ servers.db.password }}"
    priv: "{{ servers.db.database }}.*:ALL"
    state: present

- name: ensure mysql daemon is started
  service:
    name: mysql
    state: started

- name: configure mysql daemon (mysqld.cnf)
  template:
    src: mysqld.cnf.j2
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
  notify:
    - restart mysql-server

- name: copy schema.sql into ~/schema.sql
  copy:
    src: schema.sql
    dest: ~/schema.sql
    mode: 0600

- name: import schema.sql into mysql database
  mysql_db:
    state: import
    name: "{{ servers.db.database }}"
    target: ~/schema.sql
    creates: ~/schema-imported

- name: create ~/schema-imported after schema.sql is imported
  file:
    path: ~/schema-imported
    mode: 0600
    state: touch