---
- name: create database
  mysql_db:
    name: "{{ servers.db.database }}"
    state: present

# change root password
# create microservice db & user
# - name: add microservice user
#   mysql_user:
#     name: {{ db}} password={{ db_pass }} host={{ db_user_host }} priv={{ db_name }}.*:ALL

# - name: ensure mysql daemon is started
#   service:
#     name: mysql
#     state: started

# - name: configure mysql daemon (mysqld.cnf)
#   template:
#     src: mysqld.cnf.j2
#     dest: /etc/mysql/mysql.conf.d/mysqld.cnf
#   notify:
#     - restart mysql-server
