---
- name: install mysql-server
  sudo: yes
  apt: name=mysql-server update_cache=yes

- name: ensure mysql is running
  sudo: yes
  service: name=mysql state=running

- name: copy mysqld.cnf
  sudo: yes
  copy: mode=0644 src=files/db/mysqld.cnf dest=/etc/mysql/mysql.conf.d/mysqld.cnf
  notify:
    - restart mysql
