---
- name: install nodejs
  sudo: True
  apt: update_cache=yes name=nodejs state=present

- name: install daemon
  sudo: True
  apt: name=daemon state=present

- name: install httpie
  sudo: yes
  apt: name=httpie

- name: link nodejs to node
  sudo: True
  file: src=/usr/bin/nodejs dest=/usr/local/bin/node state=link

- name: install npm
  sudo: True
  apt: name=npm state=present

- name: install npm packages for exampleapp
  npm: path=/vagrant/rpc-service/

- name: copy exampleapp service into systemd
  sudo: yes
  template: force=yes src=templates/exampleapp/exampleapp.service.j2 dest=/etc/systemd/system/exampleapp.service mode=0751

- name: restart exampleapp
  sudo: yes
  service: name=exampleapp state=restarted

# - name: install pm2
#   sudo: True
#   npm: name=pm2 global=yes

# - name: record pm2 task list
#   command: pm2 list
#   register: pm2_list

# - name: restart exampleapp if already running
#   command: pm2 restart exampleapp
#   when: "pm2_list.stdout.find('exampleapp') > -1"

# - name: run exampleapp using pm2
#   command:
#     pm2 start --watch --name exampleapp /vagrant/rpc-service/app.js 
#     -- {{ lookup('file', 'files/exampleapp/process-order') }}
#     --port {{ exampleapp_host }}  --proxy-port {{ varnish_port }} --address {{ exampleapp_host}}
#   when: "pm2_list.stdout.find('exampleapp') == -1"