---
- name: install nodejs
  sudo: True
  apt: update_cache=yes name=nodejs state=present

- name: install daemon
  sudo: True
  apt: name=daemon state=present

- name: link nodejs to node
  sudo: True
  file: src=/usr/bin/nodejs dest=/usr/local/bin/node state=link

- name: install npm
  sudo: True
  apt: name=npm state=present

- name: install npm packages for exampleapp
  npm: path=/vagrant/rpc-service/

- name: install pm2
  sudo: True
  npm: name=pm2 global=yes

- name: run exampleapp using pm2
  shell: pm2 start --watch node /vagrant/rpc-service/app.js -- {{ lookup('file', 'files/exampleapp/process-order') }}