---
- name: install nodejs
  sudo: True
  apt: update_cache=yes name=nodejs state=present

- name: install daemon
  sudo: True
  apt: name=daemon state=present

- name: link nodejs to node
  sudo: True
  file: src=/usr/bin/nodejs dest=/usr/local/bin/node state=link

- name: install npm
  sudo: True
  apt: name=npm state=present

- name: install npm packages for exampleapp
  npm: path=/vagrant/rpc-service/

- name: start exampleapp as daemon
  shell: daemon -- /vagrant/script.sh