---
- name: install libmysqlclient-dev
  sudo: True
  apt: name=libmysqlclient-dev

- name: install libpython-dev
  sudo: True
  apt: name=libpython-dev

- name: install python2.7
  sudo: True
  apt: name=python2.7

- name: install python-pip
  sudo: True
  apt: name=python-pip

- name: install virtualenv
  sudo: True
  apt: name=python-virtualenv

- name: install python-mysqldb
  sudo: True
  apt: name=python-mysqldb

- name: install user-interfaces requirements.txt
  pip: virtualenv=/vagrant/ui/venv requirements=/vagrant/ui/requirements.txt

- name: install nodejs
  sudo: True
  apt: update_cache=yes name=nodejs state=present

- name: link nodejs to node
  sudo: True
  file: src=/usr/bin/nodejs dest=/usr/local/bin/node state=link

- name: install npm
  sudo: True
  apt: name=npm state=present

- name: install bower
  sudo: True
  npm: name=bower global=yes state=present

- name: install bower dependencies
  command: /usr/local/bin/bower install
  args:
    chdir: /vagrant/ui/
  tags:
    - install-bower-json

# - name: run user interface
#   command: venv/bin/python manage.py runserver --port 5000 --host 192.168.33.11 --reload
#   async: true
#   poll: 0
#   args:
#     chdir: /vagrant/ui/
#   environment:
#     APP_CONFIG: development
#     DB_NAME: microservice
#     DB_USER: microservice
#     DB_PASS: AWe*apei9ue$s1u
#     DB_HOST: 192.168.33.12
#     DB_PORT: 3306
#     
#     

- name: copy user-interface service into systemd
  sudo: yes
  copy: src=files/ui/user-interface.service dest=/etc/systemd/system/ mode=0751

- name: start user-interface service
  sudo: yes
  command: systemctl start user-interface

