sudo: required

language: python

python:
  -  "2.7_with_system_site_packages"

install:
  - sudo pip install --upgrade pip
  - sudo pip install requests
  - sudo pip install mysql-python simplemysql

services:
  - docker

before_install:
  - docker pull mariusm/ubuntu-mariadb
  - docker run -d -p 3306:3306 mariusm/ubuntu-mariadb
  - curl https://repo.varnish-cache.org/debian/GPG-key.txt | sudo apt-key add -
  - echo "deb https://repo.varnish-cache.org/ubuntu/ precise varnish-4.0" | sudo tee /etc/apt/sources.list.d/varnish-cache.list
  - sudo apt-get -q update
  - sudo apt-get -y install varnish
  - sudo apt-get -y install python-dev libmysqlclient-dev
  - sudo cp logreader/test/test_default.vcl /etc/varnish/default.vcl
  - sudo service varnish restart

before_script:
  - pwd
  - cd logreader/test
  - docker-machine ls
