sudo: required

language: python

python:
  -  "2.7_with_system_site_packages"

install:
  - sudo pip install --upgrade pip
  - sudo pip install requests
  - sudo pip install mysql-python simplemysql

services:
  - mysql

env:
  global:
    - USER=zipnish
    - PASS=secret

before_install:
  - curl https://repo.varnish-cache.org/debian/GPG-key.txt | sudo apt-key add -
  - echo "deb https://repo.varnish-cache.org/ubuntu/ precise varnish-4.0" | sudo tee /etc/apt/sources.list.d/varnish-cache.list
  - sudo apt-get -q update
  - sudo apt-get -y install varnish
  - sudo apt-get -y install python-dev libmysqlclient-dev
  - sudo cp logreader/test/test_default.vcl /etc/varnish/default.vcl
  - sudo service varnish restart
  - echo "CREATE USER '$USER' IDENTIFIED BY '$PASS'" | mysql -u root --default-character-set=utf8
  - echo "REVOKE ALL PRIVILEGES ON *.* FROM '$USER'@'%'; FLUSH PRIVILEGES" | mysql -u root --default-character-set=utf8
  - echo "GRANT SELECT ON *.* TO '$USER'@'%'; FLUSH PRIVILEGES" | mysql -u root --default-character-set=utf8
  - echo "GRANT ALL PRIVILEGES ON *.* TO '$USER'@'%' WITH GRANT OPTION; FLUSH PRIVILEGES" | mysql -u root --default-character-set=utf8
  - mysqladmin shutdown

before_script:
  - pwd
  - echo $USER
  - echo $PASS