---
# handlers file for mysql-server
- name: restart mysql-server
  service:
    name: mysql
    state: restarted

# import schema.sql on database creation
- name: import schema.sql
  mysql_db:
    state: import
    name: "{{ servers.db.database }}"
    target: ~/schema.sql