---
- name: get directory listing for app/static/libs/
  file:
    path: "{{ path }}/app/static/libs"
    state: directory

- name: get directory listing for app/static/libs/
  command: "ls {{ path }}/app/static/libs"
  register: bower_libs

- name: install bower dependencies
  sudo: no
  when: bower_libs.stdout == ""
  bower:
    path: "{{ path }}"
    state: present