---
- name: Backend
  hosts: backend
  sudo: yes
  roles:
    - update-cache
    - libpython-dev
    - libmysqlclient-dev
    - python
    - python-virtualenv
    - python-mysqldb
    - {
        role: python-pip,
        virtualenv: '/vagrant/logreader/venv',
        requirements: '/vagrant/logreader/requirements.txt'
      }
    - apt-transport-https
    - varnish
    - siege
    - siege-varnish
    - log-reader