---
- name: Example Application
  hosts: exampleapp
  sudo: yes
  roles:
    - update-cache
    - httpie
    - nodejs
    - {
        role: npm,
        path: /vagrant/rpc-service/
      }
    - exampleapp