---
- name: User Interface
  hosts: ui
  sudo: yes
  roles:
    - mysql-client
    - libmysqlclient-dev
    - libpython-dev
    - python
    - python-virtualenv
    - {
        role: python-pip,
        virtualenv: '/vagrant/ui/venv',
        requirements: '/vagrant/ui/requirements.txt'
      }
    - python-mysqldb
    - nodejs
    - npm
    - bower
